spring.application.name=demo
spring.datasource.url=jdbc:postgresql://demo-postgres:5432/demo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=health,mappings
management.endpoint.mappings.enabled=true
server.error.include-message=always
spring.sql.init.mode=always
logging.level.org.springframework.web=TRACE
server.error.include-stacktrace=always
logging.level.org.springframework.web=TRACE
server.error.include-stacktrace=always
